
import { Restaurant, PriceLevel, TravelTime } from './types';

// Helper to create simple daily schedule
// 0 = Sunday, 1 = Monday, ..., 6 = Saturday
const standardSchedule = (lunchStart: string, lunchEnd: string, dinnerStart: string, dinnerEnd: string) => {
  const slots = [{ open: lunchStart, close: lunchEnd }, { open: dinnerStart, close: dinnerEnd }];
  return { 1: slots, 2: slots, 3: slots, 4: slots, 5: slots, 6: slots, 0: slots };
};

// Helper for full day open (e.g. 11:00 to 22:00 straight)
const fullDaySchedule = (start: string, end: string) => {
  const slots = [{ open: start, close: end }];
  return { 1: slots, 2: slots, 3: slots, 4: slots, 5: slots, 6: slots, 0: slots };
};

// Helper for late night places (e.g. 17:00 to 02:00)
const nightSchedule = (start: string, end: string) => {
  const slots = [{ open: start, close: end }];
  return { 1: slots, 2: slots, 3: slots, 4: slots, 5: slots, 6: slots, 0: slots };
};

export const PRICE_OPTIONS: { value: PriceLevel; label: string }[] = [
  { value: '1-200', label: '日常一餐 (1~200元)' },
  { value: '200-400', label: '對自己好一點 (200~400元)' },
  { value: '400-600', label: '約會大餐 (400~600元)' },
  { value: '600-1500', label: '頂級紀念 (600~1500元)' },
];

export const TIME_OPTIONS: { value: TravelTime; label: string }[] = [
  { value: '5', label: '5 分鐘左右' },
  { value: '10', label: '10 分鐘左右' },
  { value: '15', label: '15 分鐘左右' },
  { value: '20', label: '20 分鐘以上' },
];

// Data parsed from user's Google Maps list
// Center: Taichung West Dist., Zhongshan Rd. No. 469 (Near SOGO/Science Museum)
// Estimated travel times: 
// - SOGO/Science Museum area: ~3-5 mins
// - China Night Market (Zhonghua Rd): ~5-8 mins
// - Upward Market (Xiangshang Market): ~8-12 mins
// - Other areas: ~10-15 mins

export const RESTAURANT_LIST: Restaurant[] = [
  // --- 1-200 Range (Everyday Meals) ---
  {
    id: 'c1',
    name: '一沐日 台中中華店',
    emoji: '🧋',
    priceRange: '1-200',
    travelTimeMinutes: 7,
    travelTimeCategory: '10',
    address: '台中市中區中華路一段',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=一沐日+台中中華店',
    schedule: fullDaySchedule('10:00', '22:00'),
  },
  {
    id: 'c2',
    name: 'S&B姐 弟早午餐',
    emoji: '🥪',
    priceRange: '1-200',
    travelTimeMinutes: 6,
    travelTimeCategory: '10',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=S%26B姐弟早午餐',
    schedule: standardSchedule('07:00', '14:00', '', ''),
  },
  {
    id: 'c3',
    name: '默More 早午餐',
    emoji: '🥓',
    priceRange: '1-200',
    travelTimeMinutes: 5,
    travelTimeCategory: '5',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=默More早午餐',
    schedule: standardSchedule('08:00', '15:00', '', ''),
  },
  {
    id: 'c4',
    name: '禾巧味 手工蛋餅',
    emoji: '🍳',
    priceRange: '1-200',
    travelTimeMinutes: 8,
    travelTimeCategory: '10',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=禾巧味手工蛋餅',
    schedule: standardSchedule('06:00', '13:00', '', ''),
  },
  {
    id: 'c5',
    name: '伍宅晨食-民生總店',
    emoji: '🥯',
    priceRange: '1-200',
    travelTimeMinutes: 10,
    travelTimeCategory: '10',
    address: '台中市西區民生路',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=伍宅晨食-民生總店',
    schedule: standardSchedule('06:00', '13:30', '', ''),
  },
  {
    id: 'c6',
    name: '土木公社炭烤土司-五廊店',
    emoji: '🍞',
    priceRange: '1-200',
    travelTimeMinutes: 11,
    travelTimeCategory: '15',
    address: '台中市西區五廊街',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=土木公社炭烤土司-五廊店',
    schedule: standardSchedule('06:30', '13:00', '', ''),
  },
  {
    id: 'c7',
    name: '解憂牛肉麵 中區成功店',
    emoji: '🍜',
    priceRange: '1-200',
    travelTimeMinutes: 8,
    travelTimeCategory: '10',
    address: '台中市中區成功路',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=解憂牛肉麵+中區成功店',
    schedule: standardSchedule('11:00', '14:00', '17:00', '20:30'),
  },
  {
    id: 'c8',
    name: '早安公雞_農場晨食_篤行店',
    emoji: '🐔',
    priceRange: '1-200',
    travelTimeMinutes: 5,
    travelTimeCategory: '5',
    address: '台中市西區篤行路',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=早安公雞_農場晨食_篤行店',
    schedule: fullDaySchedule('06:00', '13:30'),
  },
  {
    id: 'c9',
    name: '火曜二代目 拉麵',
    emoji: '🍜',
    priceRange: '1-200',
    travelTimeMinutes: 9,
    travelTimeCategory: '10',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=火曜二代目',
    schedule: standardSchedule('11:30', '14:00', '17:30', '21:00'),
  },
  {
    id: 'c10',
    name: '小丼作丨親子丼',
    emoji: '🍚',
    priceRange: '1-200',
    travelTimeMinutes: 6,
    travelTimeCategory: '10',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=小丼作',
    schedule: standardSchedule('11:30', '13:30', '17:30', '19:30'),
  },
  {
    id: 'c11',
    name: '家味現炒',
    emoji: '🥘',
    priceRange: '1-200',
    travelTimeMinutes: 7,
    travelTimeCategory: '10',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=家味現炒',
    schedule: standardSchedule('11:00', '14:00', '17:00', '21:00'),
  },
  {
    id: 'c12',
    name: '羅娃麵包坊(四維店)',
    emoji: '🥐',
    priceRange: '1-200',
    travelTimeMinutes: 10,
    travelTimeCategory: '10',
    address: '台中市西區四維街',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=羅娃麵包坊(四維店)',
    schedule: fullDaySchedule('10:00', '20:00'),
  },
  {
    id: 'c13',
    name: '沼澤咖哩瑞豐店',
    emoji: '🍛',
    priceRange: '1-200',
    travelTimeMinutes: 12,
    travelTimeCategory: '15',
    address: '台中市',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=沼澤咖哩瑞豐店',
    schedule: standardSchedule('11:00', '14:30', '17:00', '20:30'),
  },
  {
    id: 'c14',
    name: '好佳亭嘉義火雞肉飯',
    emoji: '🍚',
    priceRange: '1-200',
    travelTimeMinutes: 6,
    travelTimeCategory: '10',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=好佳亭嘉義火雞肉飯',
    schedule: fullDaySchedule('10:30', '20:00'),
  },
  {
    id: 'c15',
    name: '小豬很忙蔬果滷味（美村店）',
    emoji: '🥬',
    priceRange: '1-200',
    travelTimeMinutes: 4,
    travelTimeCategory: '5',
    address: '台中市西區美村路',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=小豬很忙蔬果滷味（美村店）',
    schedule: nightSchedule('16:00', '23:30'),
  },
  {
    id: 'c16',
    name: '吃吃雞 鹹水雞｜中華路夜市',
    emoji: '🍗',
    priceRange: '1-200',
    travelTimeMinutes: 8,
    travelTimeCategory: '10',
    address: '台中市中區中華路',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=吃吃雞+鹹水雞',
    schedule: nightSchedule('17:00', '00:00'),
  },
  {
    id: 'c17',
    name: '黃家胡椒餅',
    emoji: '🍘',
    priceRange: '1-200',
    travelTimeMinutes: 9,
    travelTimeCategory: '10',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=黃家胡椒餅',
    schedule: standardSchedule('14:00', '19:00', '', ''),
  },
  {
    id: 'c18',
    name: '品燒炭烤美食店',
    emoji: '🍡',
    priceRange: '1-200',
    travelTimeMinutes: 8,
    travelTimeCategory: '10',
    address: '台中市中區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=品燒炭烤美食店',
    schedule: nightSchedule('17:30', '01:00'),
  },
  {
    id: 'c19',
    name: '鵝媽媽',
    emoji: '🦢',
    priceRange: '1-200',
    travelTimeMinutes: 9,
    travelTimeCategory: '10',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=鵝媽媽',
    schedule: nightSchedule('17:00', '01:00'),
  },
  {
    id: 'c20',
    name: '炸魂雞排-西區向上店',
    emoji: '🍗',
    priceRange: '1-200',
    travelTimeMinutes: 10,
    travelTimeCategory: '10',
    address: '台中市西區向上路',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=炸魂雞排-西區向上店',
    schedule: nightSchedule('15:00', '22:30'),
  },
  {
    id: 'c21',
    name: '史溫侯 Swinhoe 咖啡',
    emoji: '☕',
    priceRange: '1-200',
    travelTimeMinutes: 8,
    travelTimeCategory: '10',
    address: '台中市',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=史溫侯+Swinhoe',
    schedule: fullDaySchedule('12:00', '19:00'),
  },
  {
    id: 'c22',
    name: '彭記酥皮蚵阿煎',
    emoji: '🦪',
    priceRange: '1-200',
    travelTimeMinutes: 7,
    travelTimeCategory: '10',
    address: '台中市北區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=彭記酥皮蚵阿煎',
    schedule: standardSchedule('11:00', '14:00', '16:00', '20:00'),
  },
  {
    id: 'c23',
    name: '頂吉古早味火雞肉飯',
    emoji: '🍚',
    priceRange: '1-200',
    travelTimeMinutes: 9,
    travelTimeCategory: '10',
    address: '台中市中區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=頂吉古早味火雞肉飯',
    schedule: standardSchedule('10:30', '19:30', '', ''),
  },
  {
    id: 'c24',
    name: '王哥肉丸向上店',
    emoji: '🥣',
    priceRange: '1-200',
    travelTimeMinutes: 10,
    travelTimeCategory: '10',
    address: '台中市西區向上北路',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=王哥肉丸向上店',
    schedule: fullDaySchedule('10:00', '21:00'),
  },
  {
    id: 'c25',
    name: '大台北滷味',
    emoji: '🍢',
    priceRange: '1-200',
    travelTimeMinutes: 9,
    travelTimeCategory: '10',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=大台北滷味',
    schedule: nightSchedule('16:00', '23:00'),
  },
  {
    id: 'c26',
    name: '中美街蚵嗲',
    emoji: '🦪',
    priceRange: '1-200',
    travelTimeMinutes: 9,
    travelTimeCategory: '10',
    address: '台中市西區中美街',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=中美街蚵嗲',
    schedule: standardSchedule('14:00', '19:00', '', ''),
  },
  {
    id: 'c27',
    name: '協力旺雞排向上市場店',
    emoji: '🍗',
    priceRange: '1-200',
    travelTimeMinutes: 10,
    travelTimeCategory: '10',
    address: '台中市西區中美街',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=協力旺雞排向上市場店',
    schedule: nightSchedule('15:00', '23:00'),
  },
  {
    id: 'c28',
    name: '飯丸屋-台中向上店',
    emoji: '🍙',
    priceRange: '1-200',
    travelTimeMinutes: 10,
    travelTimeCategory: '10',
    address: '台中市西區向上路',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=飯丸屋-台中向上店',
    schedule: standardSchedule('06:30', '13:00', '16:00', '19:00'),
  },
  {
    id: 'c29',
    name: '五桐號WooTEA台中向上店',
    emoji: '🥤',
    priceRange: '1-200',
    travelTimeMinutes: 10,
    travelTimeCategory: '10',
    address: '台中市西區向上路',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=五桐號WooTEA台中向上店',
    schedule: fullDaySchedule('10:00', '21:00'),
  },
  {
    id: 'c30',
    name: '廟口意麵 （向上店）',
    emoji: '🍜',
    priceRange: '1-200',
    travelTimeMinutes: 10,
    travelTimeCategory: '10',
    address: '台中市西區向上路',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=廟口意麵+向上店',
    schedule: standardSchedule('11:00', '22:00', '', ''),
  },
  {
    id: 'c31',
    name: '台北太祖魷魚羹',
    emoji: '🍲',
    priceRange: '1-200',
    travelTimeMinutes: 11,
    travelTimeCategory: '15',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=台北太祖魷魚羹',
    schedule: standardSchedule('10:00', '21:00', '', ''),
  },
  {
    id: 'c32',
    name: '老蔡上海生煎包',
    emoji: '🥟',
    priceRange: '1-200',
    travelTimeMinutes: 9,
    travelTimeCategory: '10',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=老蔡上海生煎包',
    schedule: standardSchedule('12:00', '20:00', '', ''),
  },
  {
    id: 'c33',
    name: '統元豆花向上店',
    emoji: '🍮',
    priceRange: '1-200',
    travelTimeMinutes: 10,
    travelTimeCategory: '10',
    address: '台中市西區向上北路',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=統元豆花向上店',
    schedule: fullDaySchedule('11:00', '22:00'),
  },
  {
    id: 'c34',
    name: '江家餛飩',
    emoji: '🍜',
    priceRange: '1-200',
    travelTimeMinutes: 11,
    travelTimeCategory: '15',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=江家餛飩',
    schedule: standardSchedule('11:00', '20:00', '', ''),
  },
  {
    id: 'c35',
    name: '馬椰爺 咖椰吐司專賣',
    emoji: '🍞',
    priceRange: '1-200',
    travelTimeMinutes: 8,
    travelTimeCategory: '10',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=馬椰爺',
    schedule: nightSchedule('17:00', '23:00'),
  },
  {
    id: 'c36',
    name: '摩斯漢堡 美村向上店',
    emoji: '🍔',
    priceRange: '1-200',
    travelTimeMinutes: 10,
    travelTimeCategory: '10',
    address: '台中市西區美村路',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=摩斯漢堡+美村向上店',
    schedule: fullDaySchedule('06:00', '23:00'),
  },
  {
    id: 'c37',
    name: '大拇哥 牛肉麵/蒸餃',
    emoji: '🥟',
    priceRange: '1-200',
    travelTimeMinutes: 9,
    travelTimeCategory: '10',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=大拇哥',
    schedule: standardSchedule('11:00', '14:00', '17:00', '20:30'),
  },
  {
    id: 'c38',
    name: '嗎哪關東煮',
    emoji: '🍢',
    priceRange: '1-200',
    travelTimeMinutes: 9,
    travelTimeCategory: '10',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=嗎哪關東煮',
    schedule: nightSchedule('16:00', '22:00'),
  },
  {
    id: 'c39',
    name: '就醬滷',
    emoji: '🥘',
    priceRange: '1-200',
    travelTimeMinutes: 8,
    travelTimeCategory: '10',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=就醬滷',
    schedule: nightSchedule('17:00', '23:00'),
  },
  {
    id: 'c40',
    name: '多那之台中復中門市',
    emoji: '🍰',
    priceRange: '1-200',
    travelTimeMinutes: 12,
    travelTimeCategory: '15',
    address: '台中市東區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=多那之台中復中門市',
    schedule: fullDaySchedule('07:00', '23:00'),
  },
  {
    id: 'c41',
    name: '走曼一點 鹹酥雞',
    emoji: '🍗',
    priceRange: '1-200',
    travelTimeMinutes: 8,
    travelTimeCategory: '10',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=走曼一點',
    schedule: nightSchedule('17:00', '00:00'),
  },
  {
    id: 'c42',
    name: '赤香 腿庫飯/東坡肉',
    emoji: '🥩',
    priceRange: '1-200',
    travelTimeMinutes: 9,
    travelTimeCategory: '10',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=赤香',
    schedule: standardSchedule('11:00', '14:00', '17:00', '20:30'),
  },
  {
    id: 'c43',
    name: '米浪飯卷-漢口店',
    emoji: '🌯',
    priceRange: '1-200',
    travelTimeMinutes: 6,
    travelTimeCategory: '10',
    address: '台中市北區漢口路',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=米浪飯卷-漢口店',
    schedule: standardSchedule('10:00', '19:00', '', ''),
  },
  {
    id: 'c44',
    name: '惦記粉漿蛋餅',
    emoji: '🥞',
    priceRange: '1-200',
    travelTimeMinutes: 8,
    travelTimeCategory: '10',
    address: '台中市北區英才路',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=惦記粉漿蛋餅',
    schedule: standardSchedule('06:00', '13:00', '', ''),
  },
  {
    id: 'c45',
    name: '夯霸燒肉便當',
    emoji: '🍱',
    priceRange: '1-200',
    travelTimeMinutes: 9,
    travelTimeCategory: '10',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=夯霸燒肉便當',
    schedule: standardSchedule('10:30', '13:30', '16:30', '19:30'),
  },
  {
    id: 'c46',
    name: 'LaLaPoke夏威夷拌飯',
    emoji: '🥗',
    priceRange: '1-200',
    travelTimeMinutes: 5,
    travelTimeCategory: '5',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=LaLaPoke',
    schedule: standardSchedule('11:00', '20:00', '', ''),
  },
  {
    id: 'c47',
    name: '泰姆-泰式拌飯',
    emoji: '🍛',
    priceRange: '1-200',
    travelTimeMinutes: 6,
    travelTimeCategory: '10',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=泰姆-泰式拌飯',
    schedule: standardSchedule('11:00', '20:00', '', ''),
  },
  {
    id: 'c48',
    name: '柯宅食事 咖哩',
    emoji: '🍛',
    priceRange: '1-200',
    travelTimeMinutes: 7,
    travelTimeCategory: '10',
    address: '台中市北區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=柯宅食事',
    schedule: standardSchedule('11:00', '14:00', '17:00', '20:00'),
  },
  {
    id: 'c49',
    name: '微滷',
    emoji: '🥘',
    priceRange: '1-200',
    travelTimeMinutes: 8,
    travelTimeCategory: '10',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=微滷',
    schedule: nightSchedule('17:00', '23:00'),
  },
  {
    id: 'c50',
    name: '路上 Camino 飲料',
    emoji: '🥤',
    priceRange: '1-200',
    travelTimeMinutes: 6,
    travelTimeCategory: '10',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=路上+Camino',
    schedule: fullDaySchedule('10:00', '20:00'),
  },
  {
    id: 'c51',
    name: '享饌食堂',
    emoji: '🥢',
    priceRange: '1-200',
    travelTimeMinutes: 9,
    travelTimeCategory: '10',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=享饌食堂',
    schedule: standardSchedule('11:00', '14:00', '17:00', '20:30'),
  },
  {
    id: 'c52',
    name: '周記餛飩',
    emoji: '🍜',
    priceRange: '1-200',
    travelTimeMinutes: 10,
    travelTimeCategory: '10',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=周記餛飩',
    schedule: standardSchedule('11:00', '20:00', '', ''),
  },
  {
    id: 'c53',
    name: '晚奌 宵夜',
    emoji: '🌙',
    priceRange: '1-200',
    travelTimeMinutes: 9,
    travelTimeCategory: '10',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=晚奌',
    schedule: nightSchedule('17:30', '01:30'),
  },
  {
    id: 'c54',
    name: '魚日內人-炸蛋魯肉飯',
    emoji: '🍚',
    priceRange: '1-200',
    travelTimeMinutes: 9,
    travelTimeCategory: '10',
    address: '台中市西區向上路',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=魚日內人',
    schedule: nightSchedule('17:00', '00:00'),
  },
  {
    id: 'c55',
    name: '三輪車關東煮中華店',
    emoji: '🍢',
    priceRange: '1-200',
    travelTimeMinutes: 7,
    travelTimeCategory: '10',
    address: '台中市中區中華路',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=三輪車關東煮中華店',
    schedule: nightSchedule('17:00', '00:00'),
  },
  {
    id: 'c56',
    name: '旺春豐鉄板吐司',
    emoji: '🥪',
    priceRange: '1-200',
    travelTimeMinutes: 8,
    travelTimeCategory: '10',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=旺春豐鉄板吐司',
    schedule: standardSchedule('07:00', '14:00', '17:00', '01:00'),
  },

  // --- 200-400 Range (Nice Meal) ---
  {
    id: 'm1',
    name: '無貓不歡貓咪咖啡廳',
    emoji: '🐱',
    priceRange: '200-400',
    travelTimeMinutes: 5,
    travelTimeCategory: '5',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=無貓不歡貓咪咖啡廳',
    schedule: fullDaySchedule('11:00', '20:00'),
  },
  {
    id: 'm2',
    name: '京采小館',
    emoji: '🥟',
    priceRange: '200-400',
    travelTimeMinutes: 10,
    travelTimeCategory: '10',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=京采小館',
    schedule: standardSchedule('11:00', '14:00', '17:00', '21:00'),
  },
  {
    id: 'm3',
    name: '曼谷小城泰式料理',
    emoji: '🇹🇭',
    priceRange: '200-400',
    travelTimeMinutes: 9,
    travelTimeCategory: '10',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=曼谷小城泰式料理',
    schedule: standardSchedule('11:00', '14:00', '17:00', '21:00'),
  },
  {
    id: 'm4',
    name: '松葉壽司',
    emoji: '🍣',
    priceRange: '200-400',
    travelTimeMinutes: 9,
    travelTimeCategory: '10',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=松葉壽司',
    schedule: standardSchedule('11:00', '14:00', '17:00', '21:00'),
  },
  {
    id: 'm5',
    name: '禾作食堂',
    emoji: '🍚',
    priceRange: '200-400',
    travelTimeMinutes: 10,
    travelTimeCategory: '10',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=禾作食堂',
    schedule: standardSchedule('11:00', '14:30', '17:30', '20:30'),
  },
  {
    id: 'm6',
    name: '宮崎日式咖喱',
    emoji: '🍛',
    priceRange: '200-400',
    travelTimeMinutes: 11,
    travelTimeCategory: '15',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=宮崎日式咖喱',
    schedule: standardSchedule('11:00', '14:00', '17:00', '20:30'),
  },
  {
    id: 'm7',
    name: '樸樂13早午晚餐(軍福店)',
    emoji: '🥗',
    priceRange: '200-400',
    travelTimeMinutes: 25,
    travelTimeCategory: '20', // Further away in Beitun
    address: '台中市北屯區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=樸樂13早午晚餐',
    schedule: fullDaySchedule('08:00', '20:00'),
  },
  {
    id: 'm8',
    name: '雲日 食事処',
    emoji: '🍤',
    priceRange: '200-400',
    travelTimeMinutes: 8,
    travelTimeCategory: '10',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=雲日+食事処',
    schedule: standardSchedule('11:30', '14:00', '17:30', '20:30'),
  },
  {
    id: 'm9',
    name: '徐紹桓原麥烘焙所',
    emoji: '🥯',
    priceRange: '200-400',
    travelTimeMinutes: 10,
    travelTimeCategory: '10',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=徐紹桓原麥烘焙所',
    schedule: fullDaySchedule('12:00', '19:00'),
  },
  {
    id: 'm10',
    name: '龍饌鐵板燒（五權西店）',
    emoji: '🥩',
    priceRange: '200-400',
    travelTimeMinutes: 12,
    travelTimeCategory: '15',
    address: '台中市西區五權西路',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=龍饌鐵板燒',
    schedule: standardSchedule('11:00', '14:00', '17:00', '21:30'),
  },
  {
    id: 'm11',
    name: '啡文學咖啡梅川店',
    emoji: '☕',
    priceRange: '200-400',
    travelTimeMinutes: 10,
    travelTimeCategory: '10',
    address: '台中市北區梅川東路',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=啡文學咖啡梅川店',
    schedule: fullDaySchedule('08:00', '22:00'),
  },
  {
    id: 'm12',
    name: '大豐野菜館（滷菩提）素食',
    emoji: '🥗',
    priceRange: '200-400',
    travelTimeMinutes: 9,
    travelTimeCategory: '10',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=大豐野菜館',
    schedule: standardSchedule('11:00', '14:00', '17:00', '20:30'),
  },
  {
    id: 'm13',
    name: '高麗屋',
    emoji: '🇰🇷',
    priceRange: '200-400',
    travelTimeMinutes: 15,
    travelTimeCategory: '15',
    address: '台中市東區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=台中市東區高麗屋',
    schedule: standardSchedule('11:30', '14:00', '17:30', '21:00'),
  },
  {
    id: 'm14',
    name: '泰德牛排',
    emoji: '🥩',
    priceRange: '200-400',
    travelTimeMinutes: 11,
    travelTimeCategory: '15',
    address: '台中市西區向上路',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=泰德牛排',
    schedule: standardSchedule('11:00', '15:00', '17:00', '21:30'),
  },
  {
    id: 'm15',
    name: '路靡也！早午餐',
    emoji: '🥯',
    priceRange: '200-400',
    travelTimeMinutes: 8,
    travelTimeCategory: '10',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=路靡也',
    schedule: standardSchedule('09:00', '15:00', '', ''),
  },
  {
    id: 'm16',
    name: '職男嘎哩-中美店',
    emoji: '🍛',
    priceRange: '200-400',
    travelTimeMinutes: 9,
    travelTimeCategory: '10',
    address: '台中市西區中美街',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=職男嘎哩',
    schedule: standardSchedule('11:00', '14:00', '17:00', '20:30'),
  },
  {
    id: 'm17',
    name: '諾米亞鐵板燒',
    emoji: '🥩',
    priceRange: '200-400',
    travelTimeMinutes: 12,
    travelTimeCategory: '15',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=諾米亞鐵板燒',
    schedule: standardSchedule('11:30', '14:00', '17:30', '21:00'),
  },
  {
    id: 'm18',
    name: '伙房燒烤-向上店',
    emoji: '🍢',
    priceRange: '200-400',
    travelTimeMinutes: 10,
    travelTimeCategory: '10',
    address: '台中市西區向上路',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=伙房燒烤',
    schedule: nightSchedule('17:30', '02:30'),
  },
  {
    id: 'm19',
    name: 'Micoro Kitchen 可樂餅',
    emoji: '🍘',
    priceRange: '200-400',
    travelTimeMinutes: 9,
    travelTimeCategory: '10',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Micoro+Kitchen',
    schedule: standardSchedule('11:00', '14:30', '17:00', '20:00'),
  },
  {
    id: 'm20',
    name: '黝脈咖啡 Yourmind coffee',
    emoji: '☕',
    priceRange: '200-400',
    travelTimeMinutes: 12,
    travelTimeCategory: '15',
    address: '台中市中區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=黝脈咖啡',
    schedule: fullDaySchedule('11:00', '02:00'),
  },
  {
    id: 'm21',
    name: '舟倉 Cabin Cafe',
    emoji: '☕',
    priceRange: '200-400',
    travelTimeMinutes: 10,
    travelTimeCategory: '10',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=舟倉+Cabin+Cafe',
    schedule: nightSchedule('18:00', '02:00'),
  },
  {
    id: 'm22',
    name: '多肉系Succulent Curry',
    emoji: '🍛',
    priceRange: '200-400',
    travelTimeMinutes: 8,
    travelTimeCategory: '10',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=多肉系Succulent+Curry',
    schedule: standardSchedule('11:00', '14:30', '17:30', '20:30'),
  },

  // --- 400-600 Range (Date Night / Bar) ---
  // Some places listed as 200-600 or bars, mapped here for variety
  {
    id: 'd1',
    name: '壺途 (Bar)',
    emoji: '🍺',
    priceRange: '400-600',
    travelTimeMinutes: 9,
    travelTimeCategory: '10',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=壺途',
    schedule: nightSchedule('19:00', '02:00'),
  },
  {
    id: 'd2',
    name: '到港HAVEN 餐酒館',
    emoji: '🍷',
    priceRange: '400-600',
    travelTimeMinutes: 8,
    travelTimeCategory: '10',
    address: '台中市西區',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=到港HAVEN',
    schedule: nightSchedule('18:00', '01:00'),
  },
  
  // --- Convenience (Fallback) ---
  {
    id: 'conv1',
    name: '美廉社 台中篤信店',
    emoji: '🛒',
    priceRange: '1-200',
    travelTimeMinutes: 7,
    travelTimeCategory: '10',
    address: '台中市西區篤信街',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=美廉社+台中篤信店',
    schedule: fullDaySchedule('07:00', '23:59'),
  },
];

export const FUNNY_COMMENTS = [
  "就決定是它了！",
  "減肥明天再說！",
  "這個我可以！",
  "這家評價好像不錯喔！",
  "不要再猶豫了，出發！",
  "看起來真香！",
  "好久沒吃這個了！",
  "錢錢變成喜歡的形狀！",
  "吃飽才有力氣努力生活！"
];

export const INITIAL_FOOD: Restaurant = { 
  id: '0', 
  name: '準備抽籤', 
  emoji: '❓',
  priceRange: '1-200',
  travelTimeMinutes: 0,
  travelTimeCategory: '5',
  address: '',
  googleMapsUrl: '',
  schedule: {}
};
